parameters:
    mmi.navigation.navigation_config.class: Mmi\Navigation\NavigationConfig
    mmi.navigation_config.event_listener.class: NowaEra\MmiBundle\Event\EventListener\NavigationEventListener

services:
    mmi_navigation_config:
        class: "%mmi.navigation.navigation_config.class%"

    mmi_navigation_config_event_listener:
        class: "%mmi.navigation_config.event_listener.class%"
        arguments:
            - "@event_dispatcher"
            - "@mmi_navigation_config"
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }
